# Generated by Django 2.0 on 2019-08-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pttdata',
            table='crawler',
        ),
    ]
