# Generated by Django 2.0 on 2019-08-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190821_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pttdata',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
