# Generated by Django 2.0 on 2019-08-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pttdata',
        ),
    ]
